## Intro to Python and SQL Test - Group 1.

Instructions:

1. Set up jupyter notebook for this project using Kaggle, Google Colab or locally. Each point below should be in a separate cell.
2. Load up the data file `wather_data.csv` as a dataframe (file is in data folder on our repo).
3. Draw random variables between 0 and 3, where the sample size is equal to the number of obeservations in the Temperature column.
4. In markdown, shortly explain the function you used for pt 3 and it's parameters.
5. Create new column in the df called temp_add. Add these random variables to this column, show first 20.
6. Create a new column called temp_increased when you add values from temperature column and temp_add column.
7. Display descriptive statistics of temperature column and temperature increased column.
8. Analyze these values and comment on them using markdown (compare mean values, check the range, compare standard deviation and variance).
9. Change the Date column to be an index of a dataframe.
10. List months with an average temperature higher than 20.
11. Export the data as SQLite database file. Then load the file and display the contents of the database.
12. Calculate the mean temperature for each month for temperature column and temp increased column. Plot both using plotly.
13. Create a simple streamlit app which shows the original data, the mean data, and the plot.
14. Send the notebook, the database file and screenshot of the streamlit app to j.michankow@uw.edu.pl

In [40]:
import pandas as pd

weather_df = pd.read_csv("/kaggle/input/weather/weather_data.csv")

weather_df.head()

,Date,Temperature (째C),Precipitation (mm),Pressure (hPa),Cloud Cover (%)
0,2005-01-01,-2.6,65.8,1020.9,75
1,2005-02-01,7.0,11.8,1015.3,81
2,2005-03-01,16.9,3.8,1025.3,51
3,2005-04-01,13.9,144.4,1023.8,49
4,2005-05-01,18.7,125.4,1013.8,48

In [41]:
import numpy as np

sample_size = weather_df["Temperature (째C)"].shape[0]

random_variables = np.random.uniform(low=0, high=3, size=sample_size)

random_variables

array([2.25436449, 1.01839677, 2.90117522, 1.75883214, 2.03134709,
       0.28562646, 2.65522035, 2.53595295, 0.1396235 , 1.82114021,
       1.25214729, 1.49283429, 2.36726066, 0.3366798 , 0.93535236,
       0.03635719, 1.44771947, 0.39544808, 1.38231227, 0.03379506,
       2.34603908, 2.29936776, 1.83678618, 0.52991713, 2.62241639,
       1.0275114 , 0.23370534, 1.06757773, 2.08925652, 0.12677566,
       2.59067558, 2.42398315, 2.12135254, 0.08063719, 2.21754412,
       1.27299009, 1.51341676, 0.38742241, 1.00569006, 1.63996754,
       1.7419341 , 2.68327907, 1.40133406, 1.25320881, 2.95039523,
       1.76336798, 1.30625463, 0.53098463, 1.40257206, 1.23085169,
       2.61413327, 0.47635834, 2.90676713, 0.77418474, 1.71163291,
       0.17385459, 2.3167216 , 0.09411907, 2.92061485, 2.21860382,
       2.1684087 , 1.48996508, 2.40242529, 2.27840184, 0.04418953,
       0.19246228, 1.64039908, 0.62239921, 0.23345477, 0.07600885,
       1.86976262, 1.73054356, 0.13560397, 2.56142687, 1.15394707,
       1.45818011, 0.27472815, 1.18811812, 2.82439563, 1.94265698,
       2.93632463, 2.61223133, 2.34742214, 1.04557576, 2.74279884,
       2.00835666, 1.23539647, 0.01145306, 1.13101975, 2.06498409,
       0.85576321, 0.50929731, 1.40647816, 0.25672385, 2.2057205 ,
       1.88699687, 2.24910995, 2.10583627, 2.74995933, 1.75425888,
       1.39667954, 2.27099449, 2.52748945, 0.76872848, 2.8213845 ,
       0.14982458, 2.8899221 , 1.02941331, 0.29130488, 1.72730801,
       2.46836419, 0.4503224 , 0.50818673, 0.62638868, 0.8101683 ,
       0.50202992, 2.56872832, 2.02720817, 0.32254956, 2.63306292,
       1.20540032, 2.98007754, 0.62007282, 1.95828587, 0.43756935,
       1.86352488, 0.68113614, 2.06726073, 2.21184074, 0.32567193,
       1.17072257, 0.7944272 , 1.66401011, 2.83349134, 2.30527095,
       1.46312547, 2.29525015, 0.20891379, 0.97820577, 1.0754596 ,
       2.79051142, 0.03435349, 0.34751984, 0.13473651, 0.82601579,
       0.44547793, 2.09733985, 0.08786197, 0.81534315, 0.9226563 ,
       1.78157393, 2.23595611, 2.33585397, 1.16346347, 1.37850008,
       0.3661081 , 1.01514672, 2.58757655, 1.38138937, 1.05803714,
       2.06986782, 2.16404401, 1.73297651, 0.07564103, 1.37504173,
       2.65528845, 0.59716134, 1.16236738, 0.89046535, 0.51277903,
       2.7381488 , 1.26429371, 0.01558462, 1.57732782, 1.22735073,
       0.2319304 , 1.70236307, 0.57554757, 2.82378513, 0.58024187,
       2.94128173, 1.3307041 , 0.75471597, 1.32856092, 2.0223404 ,
       1.07865795, 0.94071619, 2.16300477, 2.69454018, 1.80444293,
       0.67797091, 2.22167042, 1.9315321 , 2.2081276 , 0.02242253,
       2.10735671, 1.72692365, 1.45401901, 0.08647464, 1.81677843,
       0.80676452, 0.6770263 , 0.19994723, 1.42415897, 2.06533196,
       1.81923306, 0.72060904, 0.57072183, 2.27730678, 1.25331706,
       1.53901659, 2.34797215, 1.27086581, 2.41250753, 0.58532287,
       1.5740456 , 1.12612112, 2.07823254, 2.70104748, 2.44589521,
       0.02265295, 1.66435086, 2.49439164, 1.60269124, 1.47940014,
       2.35703561, 0.1264387 , 1.8455415 , 1.49232974, 1.26200201,
       0.10920383, 2.91428017, 1.39950926, 0.29848972, 2.99280368,
       1.98828091, 0.5045142 , 2.68807345, 1.19804899, 0.68305495])

I used np.randon.uniform function, here are parameteres: low, high,size. low is lower bound, high is upper bound, and size is number of random numbers

In [42]:
weather_df["temp_add"] = random_variables

weather_df.head(20)

,Date,Temperature (째C),Precipitation (mm),Pressure (hPa),Cloud Cover (%),temp_add
0,2005-01-01,-2.6,65.8,1020.9,75,2.254364
1,2005-02-01,7.0,11.8,1015.3,81,1.018397
2,2005-03-01,16.9,3.8,1025.3,51,2.901175
3,2005-04-01,13.9,144.4,1023.8,49,1.758832
4,2005-05-01,18.7,125.4,1013.8,48,2.031347
5,2005-06-01,29.4,104.4,1019.9,68,0.285626
6,2005-07-01,29.7,61.3,1018.2,64,2.655220
7,2005-08-01,23.4,26.0,1021.8,49,2.535953
8,2005-09-01,13.7,23.5,1010.2,35,0.139624
9,2005-10-01,9.2,37.5,1018.4,59,1.821140
10,2005-11-01,1.0,82.4,1020.3,38,1.252147
11,2005-12-01,-4.6,107.2,1006.2,37,1.492834
12,2006-01-01,-5.0,99.0,1009.1,20,2.367261
13,2006-02-01,-3.8,42.0,1004.8,97,0.336680
14,2006-03-01,9.9,143.2,1013.7,66,0.935352
15,2006-04-01,15.7,110.7,1018.6,85,0.036357
16,2006-05-01,24.7,83.2,1022.5,57,1.447719
17,2006-06-01,22.0,91.8,1015.4,70,0.395448
18,2006-07-01,28.0,62.9,1023.1,82,1.382312
19,2006-08-01,24.4,37.2,1008.1,23,0.033795

In [43]:
weather_df["temp_increased"] = weather_df["Temperature (째C)"] + weather_df["temp_add"]

weather_df.head(20)

,Date,Temperature (째C),Precipitation (mm),Pressure (hPa),Cloud Cover (%),temp_add,temp_increased
0,2005-01-01,-2.6,65.8,1020.9,75,2.254364,-0.345636
1,2005-02-01,7.0,11.8,1015.3,81,1.018397,8.018397
2,2005-03-01,16.9,3.8,1025.3,51,2.901175,19.801175
3,2005-04-01,13.9,144.4,1023.8,49,1.758832,15.658832
4,2005-05-01,18.7,125.4,1013.8,48,2.031347,20.731347
5,2005-06-01,29.4,104.4,1019.9,68,0.285626,29.685626
6,2005-07-01,29.7,61.3,1018.2,64,2.655220,32.355220
7,2005-08-01,23.4,26.0,1021.8,49,2.535953,25.935953
8,2005-09-01,13.7,23.5,1010.2,35,0.139624,13.839624
9,2005-10-01,9.2,37.5,1018.4,59,1.821140,11.021140
10,2005-11-01,1.0,82.4,1020.3,38,1.252147,2.252147
11,2005-12-01,-4.6,107.2,1006.2,37,1.492834,-3.107166
12,2006-01-01,-5.0,99.0,1009.1,20,2.367261,-2.632739
13,2006-02-01,-3.8,42.0,1004.8,97,0.336680,-3.463320
14,2006-03-01,9.9,143.2,1013.7,66,0.935352,10.835352
15,2006-04-01,15.7,110.7,1018.6,85,0.036357,15.736357
16,2006-05-01,24.7,83.2,1022.5,57,1.447719,26.147719
17,2006-06-01,22.0,91.8,1015.4,70,0.395448,22.395448
18,2006-07-01,28.0,62.9,1023.1,82,1.382312,29.382312
19,2006-08-01,24.4,37.2,1008.1,23,0.033795,24.433795

In [44]:
a = weather_df["Temperature (째C)"].describe()
b = weather_df["temp_increased"].describe()

print("temperature:", a)
print("tempincreasewed", b)

temperature: count    240.000000
mean      13.152917
std        9.678285
min      -12.100000
25%        5.875000
50%       13.450000
75%       21.925000
max       31.500000
Name: Temperature (째C), dtype: float64
tempincreasewed count    240.000000
mean      14.600530
std        9.656561
min       -9.512423
25%        7.429201
50%       15.006880
75%       23.338332
max       33.564984
Name: temp_increased, dtype: float64

the mean temperature i,s  13.5 std is 9.68 minimum value on the dataset is -12 and maxis 31.5. the mean of temp_increased is higher than the mean of temperature. when it comes to range, temperature has larger range compared with temperatuereincreased column. Standart deviation of tempincreased higher than temperature column.

In [45]:
weather_df.set_index("Date", inplace=True)

weather_df.head()

,Temperature (째C),Precipitation (mm),Pressure (hPa),Cloud Cover (%),temp_add,temp_increased
Date,,,,,,
2005-01-01,-2.6,65.8,1020.9,75,2.254364,-0.345636
2005-02-01,7.0,11.8,1015.3,81,1.018397,8.018397
2005-03-01,16.9,3.8,1025.3,51,2.901175,19.801175
2005-04-01,13.9,144.4,1023.8,49,1.758832,15.658832
2005-05-01,18.7,125.4,1013.8,48,2.031347,20.731347

In [46]:
weather_df.columns

Index(['Temperature (째C)', 'Precipitation (mm)', 'Pressure (hPa)',
       'Cloud Cover (%)', 'temp_add', 'temp_increased'],
      dtype='object')

In [47]:
weather_df.index = pd.to_datetime(weather_df.index)

months = weather_df.index.month

avgmonth = weather_df.groupby(months)["Temperature (째C)"].mean()

result = avgmonth[avgmonth > 20]

result

Date
5    20.845
6    24.250
7    25.525
8    24.640
Name: Temperature (째C), dtype: float64

I used gemini to take months variables in second line.

I used Sir Jakub Michankow SQL notebook file in this cell. also gemini helped me in some cases

In [48]:
import sqlite3
import pandas as pd

database_file = "weather_data.db"
table_name = "weather"

weather_df.to_sql(table_name, con=sqlite3.connect(database_file), if_exists="replace", index=False)

print(f"Data exported to SQLite database: {database_file}")

conn = sqlite3.connect(database_file)
cursor = conn.cursor()

cursor.execute(f"SELECT * FROM {table_name}")
rows = cursor.fetchall()

column_names = [description[0] for description in cursor.description]
print("\nColumn Names:", column_names)
print("\nData in the Database:")
for row in rows:
    print(row)

conn.close()

Data exported to SQLite database: weather_data.db

Column Names: ['Temperature (째C)', 'Precipitation (mm)', 'Pressure (hPa)', 'Cloud Cover (%)', 'temp_add', 'temp_increased']

Data in the Database:
(-2.6, 65.8, 1020.9, 75, 2.2543644901906883, -0.3456355098093118)
(7.0, 11.8, 1015.3, 81, 1.0183967673030203, 8.01839676730302)
(16.9, 3.8, 1025.3, 51, 2.901175220004351, 19.80117522000435)
(13.9, 144.4, 1023.8, 49, 1.7588321417576758, 15.658832141757676)
(18.7, 125.4, 1013.8, 48, 2.0313470935238733, 20.731347093523873)
(29.4, 104.4, 1019.9, 68, 0.2856264616865628, 29.68562646168656)
(29.7, 61.3, 1018.2, 64, 2.655220347592781, 32.35522034759278)
(23.4, 26.0, 1021.8, 49, 2.5359529454052687, 25.93595294540527)
(13.7, 23.5, 1010.2, 35, 0.1396235013512117, 13.83962350135121)
(9.2, 37.5, 1018.4, 59, 1.8211402067107834, 11.021140206710783)
(1.0, 82.4, 1020.3, 38, 1.252147288417412, 2.252147288417412)
(-4.6, 107.2, 1006.2, 37, 1.492834289642646, -3.1071657103573536)
(-5.0, 99.0, 1009.1, 20, 2.367260661365127, -2.632739338634873)
(-3.8, 42.0, 1004.8, 97, 0.3366798012988982, -3.4633201987011017)
(9.9, 143.2, 1013.7, 66, 0.9353523600230279, 10.835352360023029)
(15.7, 110.7, 1018.6, 85, 0.03635718648733488, 15.736357186487334)
(24.7, 83.2, 1022.5, 57, 1.4477194686821626, 26.147719468682162)
(22.0, 91.8, 1015.4, 70, 0.3954480759973026, 22.3954480759973)
(28.0, 62.9, 1023.1, 82, 1.382312269378525, 29.382312269378524)
(24.4, 37.2, 1008.1, 23, 0.03379506454067405, 24.43379506454067)
(14.9, 53.4, 1006.5, 20, 2.346039082003728, 17.24603908200373)
(12.0, 113.7, 1014.7, 27, 2.2993677560333263, 14.299367756033327)
(1.6, 2.2, 1016.9, 48, 1.8367861784693407, 3.4367861784693408)
(1.9, 17.4, 1014.8, 74, 0.529917127070254, 2.429917127070254)
(0.8, 6.9, 1004.7, 22, 2.6224163877163047, 3.4224163877163045)
(2.5, 6.1, 1014.6, 51, 1.027511395464471, 3.527511395464471)
(10.9, 128.3, 1008.5, 29, 0.2337053390323105, 11.13370533903231)
(22.4, 105.5, 1018.3, 93, 1.0675777255787575, 23.467577725578757)
(18.1, 71.1, 1016.8, 53, 2.0892565234018763, 20.189256523401877)
(23.4, 14.7, 1010.3, 74, 0.1267756572743931, 23.526775657274392)
(23.1, 73.7, 1012.4, 51, 2.590675584600451, 25.690675584600452)
(23.3, 71.0, 1009.7, 69, 2.4239831498773174, 25.72398314987732)
(13.1, 26.0, 1014.7, 26, 2.1213525428984377, 15.221352542898437)
(13.6, 65.1, 1019.8, 27, 0.08063718729202318, 13.680637187292023)
(9.3, 59.8, 1010.1, 84, 2.2175441243016314, 11.517544124301633)
(-2.9, 92.4, 1017.5, 76, 1.2729900915546066, -1.6270099084453933)
(-4.2, 95.3, 1012.3, 86, 1.51341676451132, -2.6865832354886803)
(2.4, 6.8, 1011.0, 78, 0.38742241300347413, 2.787422413003474)
(8.3, 56.2, 1014.5, 91, 1.0056900563824422, 9.305690056382442)
(16.9, 93.9, 1009.8, 73, 1.6399675385040662, 18.539967538504065)
(20.6, 75.5, 1012.2, 86, 1.7419340958550493, 22.341934095855052)
(20.5, 128.5, 1009.0, 70, 2.6832790741603385, 23.18327907416034)
(29.6, 98.8, 1024.8, 27, 1.4013340569319568, 31.00133405693196)
(30.4, 24.4, 1015.2, 53, 1.2532088073372076, 31.653208807337208)
(13.2, 10.6, 1011.5, 54, 2.950395233692843, 16.15039523369284)
(8.8, 96.4, 1016.1, 97, 1.7633679768795376, 10.563367976879539)
(5.9, 4.0, 1014.4, 51, 1.306254631780667, 7.206254631780667)
(1.7, 87.9, 1013.9, 65, 0.5309846298621124, 2.230984629862112)
(3.3, 141.0, 1018.1, 35, 1.4025720629044218, 4.702572062904421)
(10.1, 86.3, 1018.8, 87, 1.2308516897676405, 11.33085168976764)
(9.5, 58.2, 1012.3, 56, 2.6141332744077577, 12.114133274407758)
(12.6, 96.5, 1012.1, 73, 0.4763583371865626, 13.076358337186562)
(15.9, 68.7, 1013.6, 33, 2.9067671340395465, 18.806767134039546)
(22.8, 81.8, 1003.5, 74, 0.7741847382367428, 23.574184738236745)
(24.9, 141.2, 1007.4, 67, 1.711632913242951, 26.61163291324295)
(30.4, 57.9, 1021.8, 26, 0.17385458599499026, 30.57385458599499)
(13.4, 144.2, 1023.2, 93, 2.3167216047365975, 15.716721604736598)
(10.7, 135.8, 1013.8, 26, 0.09411907210452164, 10.794119072104522)
(5.0, 29.4, 1017.9, 52, 2.920614848358351, 7.920614848358351)
(5.9, 10.4, 1016.6, 42, 2.218603815331784, 8.118603815331785)
(12.6, 15.1, 1030.4, 38, 2.168408696253209, 14.768408696253209)
(-2.7, 2.7, 1020.6, 38, 1.4899650753146898, -1.2100349246853104)
(8.5, 14.2, 1014.4, 55, 2.402425286150187, 10.902425286150187)
(18.1, 102.5, 1010.2, 48, 2.278401839971627, 20.37840183997163)
(22.0, 10.7, 1007.0, 79, 0.04418953163156403, 22.044189531631563)
(30.5, 47.8, 1016.0, 21, 0.19246227678376537, 30.692462276783765)
(26.8, 126.7, 1011.2, 20, 1.6403990839816611, 28.44039908398166)
(23.9, 3.5, 1007.9, 66, 0.6223992149858224, 24.52239921498582)
(16.8, 122.2, 1011.8, 88, 0.23345477474416299, 17.033454774744165)
(13.3, 42.3, 1009.6, 39, 0.07600885312593197, 13.376008853125933)
(7.5, 17.7, 1023.4, 30, 1.8697626204119606, 9.369762620411962)
(2.5, 104.5, 1019.4, 21, 1.7305435597834355, 4.2305435597834355)
(5.3, 94.3, 1015.0, 86, 0.13560396644617123, 5.4356039664461715)
(5.8, 131.6, 1022.4, 31, 2.561426865086736, 8.361426865086736)
(14.1, 110.3, 1015.4, 39, 1.1539470737264979, 15.253947073726497)
(16.9, 120.5, 1010.7, 24, 1.4581801128946827, 18.358180112894683)
(19.5, 42.3, 1022.6, 56, 0.27472815222330826, 19.774728152223307)
(25.4, 26.6, 1017.7, 57, 1.1881181152980627, 26.588118115298062)
(28.6, 112.6, 1009.8, 28, 2.824395634725237, 31.424395634725236)
(22.5, 121.0, 1014.0, 72, 1.942656982581775, 24.442656982581774)
(16.1, 148.6, 1010.6, 63, 2.9363246255289255, 19.036324625528927)
(8.8, 61.9, 1008.1, 43, 2.612231331939627, 11.412231331939628)
(5.1, 55.8, 1019.6, 93, 2.347422140400355, 7.447422140400354)
(6.4, 116.5, 1024.5, 49, 1.0455757644141113, 7.445575764414111)
(1.0, 51.1, 1008.0, 78, 2.7427988389052502, 3.7427988389052502)
(0.2, 139.6, 1017.8, 33, 2.0083566570898226, 2.2083566570898228)
(5.9, 128.8, 1011.7, 28, 1.2353964670318986, 7.1353964670318994)
(17.2, 64.3, 1012.6, 59, 0.011453056304280063, 17.21145305630428)
(21.9, 112.6, 1012.0, 85, 1.131019754228197, 23.031019754228197)
(31.5, 113.2, 1010.7, 44, 2.064984094228353, 33.56498409422835)
(24.1, 15.5, 1015.2, 92, 0.855763213481114, 24.955763213481116)
(25.7, 135.4, 1010.8, 41, 0.5092973114283785, 26.20929731142838)
(15.7, 75.8, 1016.4, 23, 1.4064781594325777, 17.106478159432577)
(14.7, 124.0, 1014.7, 45, 0.2567238456289288, 14.956723845628929)
(4.7, 48.0, 1013.8, 77, 2.2057204957013377, 6.905720495701338)
(1.4, 134.3, 1010.5, 48, 1.8869968680767228, 3.2869968680767228)
(3.0, 58.4, 1012.1, 56, 2.249109953587851, 5.249109953587851)
(0.9, 1.6, 1018.8, 94, 2.105836268089687, 3.005836268089687)
(8.7, 135.8, 1017.5, 89, 2.749959332630021, 11.44995933263002)
(15.6, 13.7, 1010.1, 37, 1.7542588756349509, 17.35425887563495)
(23.2, 47.9, 1015.5, 61, 1.3966795411198114, 24.596679541119812)
(21.9, 142.5, 1018.8, 60, 2.2709944932987436, 24.170994493298743)
(25.4, 142.6, 1006.7, 57, 2.5274894546853686, 27.927489454685368)
(22.9, 86.0, 1017.7, 53, 0.7687284792649975, 23.668728479264995)
(18.6, 94.8, 1011.7, 36, 2.821384503125918, 21.42138450312592)
(5.4, 67.3, 1017.9, 56, 0.14982458045051783, 5.549824580450518)
(3.3, 44.0, 1011.2, 44, 2.889922095545516, 6.189922095545516)
(1.9, 49.3, 1006.0, 95, 1.0294133117566748, 2.929413311756675)
(7.8, 100.9, 1006.9, 46, 0.29130488302362534, 8.091304883023625)
(-0.3, 112.9, 1015.2, 76, 1.7273080103921914, 1.4273080103921914)
(8.3, 118.7, 1016.3, 50, 2.4683641901803326, 10.768364190180334)
(20.6, 118.4, 1010.5, 25, 0.4503224017009163, 21.050322401700917)
(15.7, 13.7, 1018.2, 59, 0.5081867305755281, 16.208186730575527)
(18.4, 74.2, 1006.7, 31, 0.6263886816300587, 19.026388681630056)
(26.3, 8.6, 1014.7, 72, 0.8101682963048995, 27.1101682963049)
(23.5, 82.4, 1008.9, 90, 0.5020299157715417, 24.00202991577154)
(11.9, 66.2, 1011.7, 29, 2.5687283154280083, 14.46872831542801)
(12.1, 133.2, 1015.2, 64, 2.0272081711308836, 14.127208171130883)
(5.7, 52.6, 1010.7, 36, 0.322549558744504, 6.022549558744505)
(-2.8, 17.6, 1013.1, 45, 2.6330629241604533, -0.16693707583954653)
(-6.4, 21.4, 1020.0, 81, 1.205400317561774, -5.194599682438226)
(4.4, 114.2, 1012.1, 65, 2.9800775361839813, 7.380077536183982)
(12.0, 92.7, 1019.2, 83, 0.6200728202892916, 12.620072820289291)
(14.7, 15.2, 1009.4, 21, 1.9582858733129735, 16.658285873312973)
(25.5, 12.6, 1017.6, 73, 0.43756934724177143, 25.937569347241773)
(21.8, 105.1, 1022.2, 84, 1.8635248813181318, 23.663524881318132)
(20.4, 10.9, 1002.6, 70, 0.6811361434383898, 21.08113614343839)
(22.9, 123.3, 1011.0, 72, 2.0672607328277444, 24.967260732827743)
(14.9, 105.9, 1017.9, 55, 2.2118407412803585, 17.11184074128036)
(10.7, 12.2, 1014.0, 45, 0.3256719332600173, 11.025671933260016)
(4.3, 12.7, 1016.9, 48, 1.1707225749955081, 5.4707225749955075)
(1.8, 148.0, 1012.0, 40, 0.7944272026600336, 2.5944272026600337)
(-6.3, 56.1, 1015.4, 30, 1.6640101097062732, -4.635989890293727)
(7.2, 55.6, 1014.2, 59, 2.8334913380330167, 10.033491338033016)
(9.8, 121.9, 1020.8, 30, 2.3052709515870764, 12.105270951587077)
(18.4, 142.1, 1016.3, 55, 1.4631254743706743, 19.863125474370673)
(21.0, 147.9, 1016.7, 78, 2.295250150703389, 23.29525015070339)
(26.4, 113.0, 1012.9, 58, 0.20891379294466905, 26.60891379294467)
(26.7, 56.4, 1012.6, 73, 0.9782057690941116, 27.67820576909411)
(26.3, 12.5, 1012.8, 74, 1.0754596002608248, 27.375459600260825)
(16.9, 116.6, 1017.0, 43, 2.790511421115099, 19.690511421115097)
(14.0, 83.8, 1012.9, 41, 0.03435349476585625, 14.034353494765856)
(5.6, 63.6, 1016.4, 88, 0.3475198400122441, 5.9475198400122435)
(3.5, 136.0, 1025.4, 75, 0.1347365082113372, 3.634736508211337)
(-0.4, 16.7, 1019.4, 52, 0.8260157901196015, 0.42601579011960145)
(7.2, 73.9, 1013.4, 55, 0.4454779332805868, 7.645477933280587)
(8.0, 1.7, 1021.0, 39, 2.097339845135421, 10.097339845135421)
(20.4, 70.3, 1013.0, 81, 0.08786196689259218, 20.48786196689259)
(19.9, 8.4, 1004.8, 92, 0.815343154417831, 20.71534315441783)
(20.7, 17.8, 1010.0, 45, 0.92265630204814, 21.62265630204814)
(25.4, 17.6, 1005.6, 85, 1.7815739294057873, 27.181573929405786)
(23.0, 97.4, 1013.2, 92, 2.2359561140720854, 25.235956114072085)
(17.5, 111.9, 1015.1, 92, 2.3358539686432462, 19.835853968643246)
(8.0, 87.5, 1023.4, 59, 1.1634634662716543, 9.163463466271654)
(3.7, 144.3, 1016.6, 36, 1.3785000766103233, 5.078500076610323)
(-9.4, 56.2, 1013.9, 20, 0.3661081039434936, -9.033891896056506)
(-2.3, 42.9, 1019.1, 80, 1.0151467220348485, -1.2848532779651514)
(-12.1, 130.3, 1003.9, 62, 2.5875765526007224, -9.512423447399277)
(5.2, 33.5, 1016.2, 61, 1.3813893667100112, 6.581389366710011)
(17.3, 144.5, 1018.9, 44, 1.0580371419126042, 18.358037141912604)
(22.4, 1.8, 1007.6, 58, 2.0698678181343384, 24.469867818134336)
(26.3, 145.5, 1020.7, 54, 2.164044014729988, 28.46404401472999)
(22.1, 6.5, 1016.7, 22, 1.7329765143820912, 23.832976514382093)
(24.9, 133.7, 1012.9, 63, 0.0756410315098025, 24.975641031509802)
(15.0, 79.2, 1018.2, 70, 1.3750417349134296, 16.37504173491343)
(6.5, 148.9, 1026.4, 31, 2.655288445630798, 9.155288445630799)
(9.5, 11.1, 1015.9, 38, 0.5971613367400282, 10.097161336740028)
(4.4, 83.1, 1016.2, 63, 1.1623673791304387, 5.562367379130439)
(-1.1, 145.4, 1012.7, 78, 0.8904653479527532, -0.20953465204724686)
(0.1, 78.5, 1010.8, 68, 0.5127790325272668, 0.6127790325272667)
(10.6, 94.4, 1019.2, 80, 2.7381487972857013, 13.338148797285701)
(8.9, 104.4, 1010.7, 36, 1.2642937129965253, 10.164293712996525)
(19.3, 68.2, 1015.4, 93, 0.015584619770598551, 19.3155846197706)
(23.0, 94.1, 1012.6, 76, 1.5773278197788634, 24.577327819778862)
(22.0, 87.6, 1017.4, 74, 1.2273507330421, 23.2273507330421)
(24.2, 135.2, 1016.7, 66, 0.23193039684048977, 24.43193039684049)
(20.4, 6.8, 1020.2, 31, 1.702363072096935, 22.102363072096935)
(11.9, 42.1, 1012.4, 81, 0.57554756786235, 12.47554756786235)
(3.3, 142.6, 1013.7, 99, 2.8237851252710953, 6.123785125271095)
(2.9, 133.5, 1010.1, 27, 0.5802418717903234, 3.4802418717903234)
(7.0, 68.3, 1012.8, 40, 2.9412817310847013, 9.9412817310847)
(4.6, 93.0, 1016.9, 99, 1.3307041012998944, 5.930704101299894)
(10.2, 41.6, 1018.8, 89, 0.7547159705683629, 10.954715970568362)
(13.1, 28.2, 1010.4, 91, 1.3285609179935511, 14.42856091799355)
(22.1, 69.6, 1019.3, 44, 2.0223403997654126, 24.122340399765413)
(26.2, 53.0, 1021.8, 31, 1.0786579537911292, 27.27865795379113)
(27.7, 87.5, 1017.1, 34, 0.9407161896899436, 28.640716189689943)
(26.9, 11.7, 1024.4, 78, 2.163004770504986, 29.063004770504985)
(18.1, 146.2, 1011.1, 45, 2.6945401848002097, 20.794540184800212)
(8.4, 147.9, 1008.8, 45, 1.8044429304401257, 10.204442930440127)
(9.0, 104.7, 1006.1, 66, 0.6779709135361794, 9.67797091353618)
(1.0, 80.4, 1022.5, 51, 2.221670418848847, 3.221670418848847)
(10.4, 46.4, 1018.3, 29, 1.9315321004334094, 12.33153210043341)
(-3.4, 122.1, 1014.7, 35, 2.208127600338594, -1.1918723996614058)
(15.2, 102.7, 1016.4, 90, 0.02242252942009304, 15.222422529420092)
(15.6, 24.4, 1009.4, 36, 2.107356707037358, 17.707356707037356)
(18.0, 136.6, 1027.2, 42, 1.7269236538004273, 19.726923653800426)
(23.5, 123.4, 1015.6, 45, 1.454019006368184, 24.954019006368185)
(24.0, 142.5, 1015.5, 26, 0.0864746425112467, 24.086474642511245)
(26.3, 108.9, 1018.6, 33, 1.8167784265171179, 28.11677842651712)
(16.6, 92.0, 1017.4, 98, 0.8067645173538704, 17.40676451735387)
(8.3, 62.7, 1016.1, 26, 0.6770263020809463, 8.977026302080947)
(4.9, 139.9, 1011.0, 28, 0.19994722977560875, 5.099947229775609)
(10.7, 129.9, 1017.4, 67, 1.424158966518591, 12.124158966518591)
(8.6, 6.8, 1024.4, 91, 2.0653319608435967, 10.665331960843597)
(2.2, 4.0, 1021.7, 78, 1.8192330590522106, 4.019233059052211)
(10.1, 56.5, 1023.0, 58, 0.7206090417501715, 10.82060904175017)
(15.4, 121.6, 1012.4, 37, 0.5707218275401278, 15.970721827540128)
(21.8, 148.1, 1010.1, 78, 2.2773067752254295, 24.07730677522543)
(21.9, 22.6, 1014.4, 36, 1.253317062260825, 23.153317062260825)
(24.2, 89.1, 1015.3, 33, 1.5390165932829523, 25.73901659328295)
(20.0, 57.1, 1020.5, 50, 2.3479721453529243, 22.347972145352923)
(16.2, 145.5, 1006.5, 43, 1.2708658118263139, 17.470865811826314)
(11.9, 126.3, 1022.6, 79, 2.4125075330348387, 14.31250753303484)
(3.6, 125.7, 1014.2, 64, 0.5853228659594584, 4.185322865959458)
(7.9, 70.3, 1012.9, 22, 1.5740456008697512, 9.47404560086975)
(-6.1, 62.2, 1009.9, 56, 1.1261211234068824, -4.973878876593117)
(-7.3, 41.0, 1006.7, 62, 2.0782325439667133, -5.2217674560332865)
(10.7, 8.5, 1019.1, 59, 2.701047478618114, 13.401047478618114)
(18.1, 129.7, 1015.4, 74, 2.4458952059268713, 20.545895205926872)
(25.1, 121.9, 1008.6, 58, 0.022652952498008583, 25.12265295249801)
(23.6, 150.0, 1008.5, 34, 1.6643508627427726, 25.264350862742774)
(28.2, 149.5, 1013.3, 23, 2.4943916359234053, 30.694391635923406)
(24.9, 83.3, 1023.3, 44, 1.6026912393601775, 26.502691239360175)
(14.5, 115.3, 1013.7, 32, 1.4794001402528043, 15.979400140252805)
(12.7, 141.7, 1007.5, 52, 2.3570356120188642, 15.057035612018863)
(7.0, 127.4, 1013.8, 35, 0.1264386958789988, 7.126438695878999)
(-7.9, 37.1, 1013.6, 61, 1.845541502492829, -6.054458497507172)
(7.4, 67.6, 1001.5, 85, 1.4923297359735859, 8.892329735973586)
(6.9, 19.4, 1014.7, 74, 1.2620020067550837, 8.162002006755085)
(8.1, 143.1, 1013.8, 61, 0.10920383093348307, 8.209203830933482)
(16.2, 90.9, 1018.5, 53, 2.914280165918486, 19.114280165918487)
(21.5, 34.3, 1024.2, 49, 1.3995092632204456, 22.899509263220445)
(25.8, 100.8, 1020.6, 32, 0.2984897238351024, 26.098489723835105)
(23.3, 92.7, 1013.7, 32, 2.9928036772309983, 26.292803677231)
(23.0, 53.7, 1009.5, 37, 1.988280907974108, 24.988280907974108)
(14.9, 17.0, 1027.9, 51, 0.5045142043506677, 15.404514204350669)
(13.5, 100.7, 1015.3, 58, 2.6880734486926157, 16.188073448692617)
(6.6, 78.0, 1015.1, 65, 1.1980489856991139, 7.798048985699113)
(-1.9, 115.8, 1014.9, 48, 0.68305494590949, -1.2169450540905098)

In [49]:
stackpoverflow and gemini helepd me for plot session

SyntaxError: invalid syntax (<ipython-input-49-3ebfeb44c2fd>, line 1)

In [ ]:
import pandas as pd
import plotly.express as px

weather_df.index = pd.to_datetime(weather_df.index)

weather_df["Month"] = weather_df.index.month

monthly_means = weather_df.groupby('Month')[['Temperature (째C)', 'temp_increased']].mean().reset_index()

print("Monthly Mean Temperatures:")
print(monthly_means)

fig = px.line(monthly_means, x='Month', y=['Temperature (째C)', 'temp_increased'],
              title='Monthly Mean Temperature vs. Temperature Increased',
              labels={'value': 'Temperature (째C)', 'variable': 'Column'},
              markers=True)

fig.update_layout(
    xaxis_title='Month',
    yaxis_title='Temperature (째C)',
    legend_title='Column',
    xaxis=dict(tickmode='linear', tick0=1, dtick=1),  
    template='plotly_white'
)

fig.show()

In [ ]:
pip install streamlit

In [50]:
import streamlit as st
import pandas as pd
import plotly.express as px

# I USED GEMINI FOR CREATING THESE VARIABLES:
data = {
    'Date': pd.date_range(start='2023-01-01', periods=365, freq='D'),
    'Temperature (째C)': [15 + 10 * (i % 30) / 30 for i in range(365)],
}


df = pd.DataFrame(data)
df.set_index('Date', inplace=True)
df['temp_increased'] = df['Temperature (째C)'] + 2  # Simple increase of 2째C
df['Month'] = df.index.month



monthly_means = df.groupby('Month')[['Temperature (째C)', 'temp_increased']].mean().reset_index()


# CPT IS USED FOR PLOTLY LIBRARY

fig = px.line(monthly_means, x='Month', y=['Temperature (째C)', 'temp_increased'],
              title='Monthly Mean Temperature vs. Temperature Increased',
              labels={'value': 'Temperature (째C)', 'variable': 'Column'},
              markers=True)
fig.update_layout(xaxis_title='Month', yaxis_title='Temperature (째C)', template='plotly_white')


# I USED MY PYTHON PROJECT FOR THESE CODES:

st.title("weather data analysis")
st.header("orignal data")
st.write(df)
st.header("monthly mean temmp")
st.write(monthly_means)
st.header("monthly mean temp vstemp increased")
st.plotly_chart(fig)

2025-01-23 13:25:49.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.792 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.793 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.794 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.799 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.800 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.804 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.804 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.805 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-01-23 13:25:49.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()